# Generated by Django 5.0.9 on 2024-09-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_zip', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_brand', models.CharField(max_length=200)),
                ('Car_model', models.CharField(max_length=200)),
                ('Car_price', models.IntegerField(default=0)),
                ('Car_sell', models.BooleanField(default=False)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cars_models', to='app.concession')),
            ],
        ),
        migrations.CreateModel(
            name='RelationSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_sells', to='app.carmodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_sells', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_roles', models.CharField(max_length=30)),
                ('cars_sell', models.ManyToManyField(through='app.RelationSell', to='app.carmodel')),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.concession')),
            ],
        ),
        migrations.AddField(
            model_name='relationsell',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_sells', to='app.seller'),
        ),
    ]
