# Generated by Django 5.0.6 on 2024-09-25 14:25
from django.utils import timezone

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='concession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='app.concession'),
        ),
    ]
